name: .NET Core Desktop CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

      - name: Run tests
        run: dotnet test --configuration ${{ matrix.configuration }} --no-build

      - name: Publish output
        run: dotnet publish --configuration ${{ matrix.configuration }} --output ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-desktop-${{ matrix.configuration }}
          path: ./publish
